environment: production
google_verify: LVxKXzemsmQ6cX2F8DjN8cc_Dh8ta63kwAwFzFQnulI
markdown: kramdown
highlighter: rouge
permalink: /posts/:title
exclude: [sass/]
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
      line_numbers: true
